theme: jekyll-theme-minimal
title: IDM Pedals
description: Effect Pedals for the Electrosmith Daisy
show_downloads: "true"
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
